music_dbt:
  outputs:
    dev:
      dataset: music_datalake
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /opt/airflow/keys/music-pipline-165b5ccbdee5.json
      location: asia-southeast1
      method: service-account
      priority: interactive
      project: music-pipline
      threads: 1
      type: bigquery
  target: dev